### ISSUE TITLE
make navbar stay for all pages

### ISSUE THREAD

**Issue by lucereal** [laurenoutloud/everyday-games#2]
If pull request accepted lol. navbar shows for app component but when routing to game component it goes away

**Comment by laurenoutloud** [comment]
Yea lol, this issue should really be on your fork because the navbar doesn't exist here yet :P But the reason it's not showing up is because of how you set up your components/routing. 

You put the routing on index.js. So app is one route, game is another route, test is another route

You added the navbar to App.js, so that's where it appears. Your new component/route is completely isolated from App.js. You can either add the navbar to your new game component, or find a way to render your game component as a child of App.js (like how game controller is). Another solution is to move your routing to App.js and make it the highest level parent
